name: rdii
channels:
  -  conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - numba
  - rasterio
  - matplotlib
  - scikit-learn
  - pytest
  - tree  
prefix: /hpc/home/gi23/miniconda3/envs/rdii
